coverage:
  paths:
    - coverage_report.lcov
  exclude:
    - '**/Sources/TokenizerMacros/**'
    - '**/Tests/**'
testExecutionTime:
  if: false
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
