coverage:
  paths:
    - coverage_report.lcov
  badge:
    path: coverage.svg
push:
  if: is_default_branch
  message: 'docs: update by octocov [skip ci]'
testExecutionTime:
  if: false
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
