// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import CompilerPluginSupport
import PackageDescription

let tokenizerTarget = Target.target(
    name: "Tokenizer",
    dependencies: [
        "TokenizerMacros"
    ],
    swiftSettings: [
        .unsafeFlags(["-Xfrontend", "-warn-long-function-bodies=100"], .when(configuration: .debug)),
        .unsafeFlags(["-Xfrontend", "-warn-long-expression-type-checking=100"], .when(configuration: .debug)),
        .unsafeFlags(["-Xfrontend", "-strict-concurrency=complete"]),
        .enableUpcomingFeature("BareSlashRegexLiterals"),
        .enableUpcomingFeature("ExistentialAny"),
        .enableUpcomingFeature("ImplicitOpenExistentials"),
        .enableExperimentalFeature("CodeItemMacros"),
    ]
)

let package = Package(
    name: "Browser.swiftpm",
    platforms: [.macOS(.v13), .iOS(.v16)],
    dependencies: [
        .package(url: "https://github.com/Losiowaty/PlaygroundTester", "0.3.1"..<"0.4.0"),
        .package(url: "https://github.com/ordo-one/package-benchmark", "1.6.5"..<"1.7.0"),
        .package(url: "https://github.com/apple/swift-syntax", from: "509.0.0-swift-DEVELOPMENT-SNAPSHOT-2023-06-17-a"),
    ],
    targets: [
        tokenizerTarget,
        .macro(
            name: "TokenizerMacros",
            dependencies: [
                .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
                .product(name: "SwiftCompilerPlugin", package: "swift-syntax"),
            ]
        ),
        .executableTarget(
            name: "MyBenchmark",
            dependencies: [
                .product(name: "Benchmark", package: "package-benchmark"),
                "Tokenizer",
            ],
            path: "Benchmarks/MyBenchmark",
            plugins: [
                .plugin(name: "BenchmarkPlugin", package: "package-benchmark")
            ]
        ),
        .testTarget(
            name: "TokenizerTests",
            dependencies: [
                "Tokenizer"
            ]
        ),
    ]
)

#if canImport(AppleProductTypes)
    import AppleProductTypes

    package.platforms = [
        .iOS("16.1")
    ]

    package.products += [
        .iOSApplication(
            name: "My App",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .earth),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone,
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad])),
            ]
        )
    ]

    package.targets += [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                "Tokenizer",
                .product(name: "PlaygroundTester", package: "PlaygroundTester"),
            ],
            swiftSettings: [
                .define("TESTING_ENABLED", .when(configuration: .debug))
            ]
        )
    ]

    tokenizerTarget.dependencies += [
        .product(name: "PlaygroundTester", package: "PlaygroundTester")
    ]
    tokenizerTarget.swiftSettings? += [
        .define("TESTING_ENABLED", .when(configuration: .debug))
    ]
#endif
