name: Swift
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - run: swift --version
      - run: swift build
      - run: swift test --enable-experimental-swift-testing --disable-xctest --disable-build-manifest-caching
      - run: swift package lint-source-code
