name: Swift
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - run: swift --version
      - run: swift build
      - run: swift test --disable-xctest --enable-code-coverage --no-parallel
      - run: swift package lint-source-code
      - run: llvm-cov export -format="lcov" .build/debug/zyphyPackageTests.swift-testing -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" > coverage_report.lcov
      - uses: k1LoW/octocov-action@v1
