name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy
    steps:
    - uses: actions/checkout@v3
    - run: swift --version
    - run: swift build
    - run: swift test

  build-macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.0.app
        xcodebuild -version
    - name: Install Swift nightly toolchain
      run: |
        VERSION=swift-DEVELOPMENT-SNAPSHOT-2023-08-29-a
        TOOLCHAIN_URL="https://download.swift.org/development/xcode/$VERSION/$VERSION-osx.pkg"
        curl -LO $TOOLCHAIN_URL
        installer -target CurrentUserHomeDirectory -pkg $VERSION-osx.pkg
        echo "PATH=$HOME/Library/Developer/Toolchains/$VERSION.xctoolchain/usr/bin:${PATH}" >> $GITHUB_ENV
    - run: swift --version
    - run: swift build
    - run: swift test
