name: Swift
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - run: swift --version
      - run: swift build
      - run: swift test
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/kkk669/swift-format-docker:509.0.0
    steps:
      - uses: actions/checkout@v4
      - run: swift-format lint -rs Package.swift Sources/ Tests/ Benchmarks/Package.swift Benchmarks/Benchmarks/
